name: gas_detector
description: ESP32 Gas Detector Monitor App
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  intl: ^0.19.0
  vibration: ^1.8.4
  audioplayers: ^5.2.1
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
